name: "Syslog to New Relic Forwarder (via ktranslate)"
description: "Syslog server that forwards syslogs to New Relic. Uses ktranslate as the core."
version: "1.1.0"
url: "https://github.com/steventine/ktranslate"
slug: "ktranslate_syslog_hassio"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
ports:
  5143/udp: 514
options:
  new_relic_account_id: ""
  new_relic_api_key: ""
schema:
  new_relic_account_id: str
  new_relic_api_key: str